apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy
  namespace: kube-system
  labels:
    project: kubernetes
    role: descheduler
data:
  policy.yaml: |
    apiVersion: descheduler/v1alpha1
    kind: DeschedulerPolicy
    strategies:
      RemoveDuplicates:
         enabled: true
      RemovePodsViolatingInterPodAntiAffinity:
         enabled: true
      LowNodeUtilization:
         enabled: true
         params:
           nodeResourceUtilizationThresholds:
             thresholds:
               cpu : 60
               memory: 60
             targetThresholds:
               cpu : 80
               memory: 80
